# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "changjinhan"
repo_name: "autonomous-driving-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/ad-arxiv-daily.json'
json_gitpage_path: './docs/ad-arxiv-daily-web.json'
json_wechat_path: './docs/ad-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Autonomous Driving": 
        filters: ["Self-Driving", "Automated Driving", "Autonomous Vehicles"]
    "Intelligent Vehicles":
        filters: ["Connected and Automated Vehicles", "Smart Mobility",
                  "Advanced Driver Assistance Systems"]
    "Motion Planning for Vehicles":
        filters: ["Vision Language Action model for Driving", "Trajectory Planning for Driving", 
                  "Decision Making in Traffic", "End-to-End Driving", "AutoVLA"]