title: Autonomous Driving Arxiv Daily
description: Automatically Update Autonomous Driving Papers Daily using Github Actions (Update Every 12th hours)
show_downloads: true

github:
  zip_url: https://github.com/changjinhan/autonomous-driving-daily
  another_url: https://github.com/changjinhan/autonomous-driving-daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  github: changjinhan

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
